spring:
  application:
    name: service-registry

server:
  port: 8761

eureka:
  client:
   register-with-eureka: false
   fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,metrics
  endpoint:
    prometheus:
      access: UNRESTRICTED
  prometheus:
    metrics:
      export:
        enabled: true